name: wuai-beta

dependencies:
  - python~=3.11
  - pip
  - pip:

    - openai

    - pydantic
    - pydantic_settings
    - python-dotenv
    - requests
    - rich

    - black
    - flake8
    - isort
    - pytest
    - mkdocs
    # - -e .
