name: wuai-beta

dependencies:
  - python~=3.11
  - pip
  - pip:
    - pydantic #==2.9.2
    - pydantic_settings #==2.5.2
    - python-dotenv
    - requests #==2.32.3
    - rich #==13.9.2
    
    - black
    - flake8
    - isort
    - pytest
    - mkdocs
    - -e .
